const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const html = fs.readFileSync(require('node:path').join(__dirname, '../monitor.html'), 'utf8');
const source = html.slice(html.indexOf('function transmissionState('), html.indexOf('function paintTransmission('));
const context = vm.createContext({});
vm.runInContext(source, context);
const now = Date.parse('2026-09-07T20:00:00Z');
const at = ms => new Date(now + ms).toISOString();
const data = { online: true, events: [], turns: [], session: { entries: [] } };
const state = () => context.transmissionState(data, now);
assert.equal(state().active, false);
data.events.push({ at: at(-2000), text: 'heard (1800ms): New request' });
assert.equal(state().prompt.text, 'New request');
assert.equal(state().active, true);
data.session.entries.push({ type: 'user', at: at(-1950), text: 'New request in full' });
assert.equal(state().prompt.text, 'New request in full');
data.session.entries.push({ type: 'tool', at: at(-1000), name: 'Read', text: '{"file_path":"app.js"}' });
assert.equal(state().text, 'Reading a file');
data.events.push({ at: at(-500), text: 'turn ok 8000ms first-audio=5000ms' });
assert.equal(state().active, false);
data.session.entries.push({ type: 'user', at: at(-100), text: 'A second request' });
assert.equal(state().active, true);
assert.equal(state().text, 'Working on your request…');
data.online = false;
assert.equal(state().active, false);
assert.equal(state().caption, 'Voice server unavailable');
data.online = true;
assert.equal(context.transmissionState(data, now + 100000).active, false);
console.log('Passed: idle, incoming, full prompt, tool activity, completion, new request, offline, stale activity');
